# Generated by Django 3.2.12 on 2023-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_fake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripcion'),
        ),
    ]
