# Generated by Django 3.2.12 on 2023-06-21 20:05

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_socialnetwork_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_images', to='core.site')),
            ],
        ),
    ]
