# Generated by Django 3.2.12 on 2023-06-23 02:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('link', models.CharField(max_length=500, verbose_name='Enlace')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_to)),
            ],
        ),
    ]
